spring.datasource.url=jdbc:mysql://localhost:3306/caboolo?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
jdbc.max.connections=50

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# AviationStack API
aviationstack.api-key=${FLIGHT_VERIFICATION_API_KEY}
aviationstack.base-url=${FLIGHT_VERIFICATION_BASE_URL}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000

# Firebase credentials
firebase.credentials.path=${FIREBASE_CREDENTIAL_PATH}
