spring.application.name=caboolo

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Local Redis Database configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379