spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:11821/caboolo?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=pGdBXDoNMvOCRKAcoUfoBcAgDDhTwKHP
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
jdbc.max.connections=50

# AviationStack API
aviationstack.api-key=YOUR_LOCAL_AVIATIONSTACK_API_KEY
aviationstack.base-url=https://api.aviationstack.com/v1