# Railway MySQL Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Railway Redis Database configuration
spring.data.redis.url=${REDIS_URL}

# Storage provider
storage.provider=cloudinary

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# AviationStack API
aviationstack.api-key=${FLIGHT_VERIFICATION_API_KEY}
aviationstack.base-url=${FLIGHT_VERIFICATION_BASE_URL}