spring.application.name=caboolo
spring.profiles.active=local

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true