package com.caboolo.backend.review.enums;

public enum ReviewTag {
    // Positive
    PUNCTUAL,
    FRIENDLY,
    CLEAN,
    GOOD_COMMUNICATION,
    SAFE_CO_TRAVELLER,

    // Neutral
    AVERAGE,
    SLIGHTLY_LATE,
    QUIET,

    // Negative
    LATE,
    NO_SHOW,
    RUDE,
    UNSAFE,
    POOR_COMMUNICATION,

    // 5 Stars
    GREAT_CONVERSATION,
    RESPECTFUL,
    CLEAN_PASSENGER,
    HELPFUL,
    SMOOTH_RIDE,
    COOPERATIVE,
    RECOMMENDED,

    // 4 Stars
    POLITE,
    MOSTLY_ON_TIME,
    GOOD_BEHAVIOUR,
    COMFORTABLE_RIDE,
    EASY_GOING,
    RESPONSIVE,

    // 3 Stars
    AVERAGE_EXPERIENCE,
    OKAY_RIDE,
    COULD_IMPROVE_PUNCTUALITY,
    LESS_INTERACTIVE,
    NEUTRAL_EXPERIENCE,
    ACCEPTABLE_BEHAVIOUR,

    // 2 Stars
    LATE_ARRIVAL,
    UNTIDY,
    UNCOMFORTABLE_RIDE,
    DISTRACTING_BEHAVIOUR,
    INCONSIDERATE,

    // 1 Star
    VERY_LATE,
    RUDE_BEHAVIOUR,
    HARASSMENT,
    SMOKING_DURING_RIDE,
    VEHICLE_UNCLEAN,
    RECKLESS_BEHAVIOUR,
    ABUSIVE_LANGUAGE,
    FELT_UNSAFE
}
